#tomcat config
server :
  port : 8081
  tomcat :
    max-threads : 128
    min-spare-threads : 5
    uri-encoding : UTF-8
spring :
  servlet :
    multipart :
      max-file-size : 10MB #设置单个文件的最大长度
      max-request-size : 100MB # 设置最大的请求文件的大小
      enabled: true
  mvc :   #静态文件
    static-path-pattern : /static/**
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource :
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.103:3306/flower_xin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  aop:
    proxy-target-class: false
mybatis :
  mapperLocations : classpath*:mybatis/*.xml #实体扫描，多个package用逗号或者分号分隔
  executor-type : reuse #默认的执行器SIMPLE、执行器重用REUSE、执行器重用语句批量更新BATCH
  type-aliases-package : com.*.dao
  configuration :
    map-underscore-to-camel-case : true
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level:
    root: info
  path: ./logs
  config: classpath:logback-dev.xml
